/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"
#include <stdio.h>


float compute_6(char *host,float a,float b,char op) {
	CLIENT *clnt;
	float  *result_1;
	values  add_6_arg;
	float  *result_2;
	values  sub_6_arg;
	float  *result_3;
	values  mul_6_arg;
	float  *result_4;
	values  div_6_arg;

	if(op=='+'){

		add_6_arg.num[0]=a;
		add_6_arg.num[1]=b;
		add_6_arg.operation=op;

		clnt = clnt_create (host, COMPUTE, COMPUTE_VERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}

		result_1 = add_6(&add_6_arg, clnt);
		if (result_1 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		clnt_destroy (clnt);

		return (*result_1);	
	}

	else if(op=='-'){
		sub_6_arg.num[0]=a;
		sub_6_arg.num[1]=b;
		sub_6_arg.operation=op;

		clnt = clnt_create (host, COMPUTE, COMPUTE_VERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}

		result_2 = sub_6(&sub_6_arg, clnt);
		if (result_2 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		clnt_destroy (clnt);

		return (*result_2);	
	}

	else if(op=='*'){
		mul_6_arg.num[0]=a;
		mul_6_arg.num[1]=b;
		mul_6_arg.operation=op;

		clnt = clnt_create (host, COMPUTE, COMPUTE_VERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}

		result_3 = mul_6(&mul_6_arg, clnt);
		if (result_3 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		clnt_destroy (clnt);

		return (*result_3);	
	}

	else if(op=='/'){
		if(b==0){
			printf("You are trying to divide by zero. Please insert a valid number.\n");
			exit(0);
		}
		else{
			div_6_arg.num[0]=a;
			div_6_arg.num[1]=b;
			div_6_arg.operation=op;

			clnt = clnt_create (host, COMPUTE, COMPUTE_VERS, "udp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}

			result_4 = div_6(&div_6_arg, clnt);
			if (result_4 == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}

			clnt_destroy (clnt);

			return (*result_4);
		}	
	}

}


int main (int argc, char *argv[]) {
	char *host;

	float number1,number2;
	char oper;
	printf("Enter the Operator followed by 2 numbers:\n");
	scanf("%c",&oper);
	scanf("%f",&number1);
	scanf("%f",&number2);
	host = argv[1];
	printf("Answer= %f\n",compute_6 (host,number1,number2,oper));
	exit(0);

}
