/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "IDL.h"

bool_t
xdr_values (XDR *xdrs, values *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->num, 2,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->operation))
		 return FALSE;
	return TRUE;
}
