/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"

float *
add_6_svc(values *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = argp->num[0] + argp->num[1];

	return &result;
}

float *
sub_6_svc(values *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = argp->num[0] - argp->num[1];

	return &result;
}

float *
mul_6_svc(values *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = argp->num[0] * argp->num[1];

	return &result;
}

float *
div_6_svc(values *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = argp->num[0] / argp->num[1];

	return &result;
}
